// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package designpattern_callback.proxies;

public class PersonListOperation
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject personListOperationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DesignPattern_Callback.PersonListOperation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OperationLabel("OperationLabel"),
		_NrPeople("_NrPeople"),
		PersonListOperation_Person("DesignPattern_Callback.PersonListOperation_Person"),
		PersonListOperation_Project("DesignPattern_Callback.PersonListOperation_Project");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PersonListOperation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DesignPattern_Callback.PersonListOperation"));
	}

	protected PersonListOperation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject personListOperationMendixObject)
	{
		if (personListOperationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DesignPattern_Callback.PersonListOperation", personListOperationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DesignPattern_Callback.PersonListOperation");

		this.personListOperationMendixObject = personListOperationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PersonListOperation.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static designpattern_callback.proxies.PersonListOperation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return designpattern_callback.proxies.PersonListOperation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static designpattern_callback.proxies.PersonListOperation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("DesignPattern_Callback.ReassignOperation", mendixObject.getType()))
			return designpattern_callback.proxies.ReassignOperation.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DesignPattern_Callback.RemoveOperation", mendixObject.getType()))
			return designpattern_callback.proxies.RemoveOperation.initialize(context, mendixObject);

		return new designpattern_callback.proxies.PersonListOperation(context, mendixObject);
	}

	public static designpattern_callback.proxies.PersonListOperation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return designpattern_callback.proxies.PersonListOperation.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OperationLabel
	 */
	public final java.lang.String getOperationLabel()
	{
		return getOperationLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of OperationLabel
	 */
	public final java.lang.String getOperationLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OperationLabel.toString());
	}

	/**
	 * Set value of OperationLabel
	 * @param operationlabel
	 */
	public final void setOperationLabel(java.lang.String operationlabel)
	{
		setOperationLabel(getContext(), operationlabel);
	}

	/**
	 * Set value of OperationLabel
	 * @param context
	 * @param operationlabel
	 */
	public final void setOperationLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operationlabel)
	{
		getMendixObject().setValue(context, MemberNames.OperationLabel.toString(), operationlabel);
	}

	/**
	 * @return value of _NrPeople
	 */
	public final java.lang.Integer get_NrPeople()
	{
		return get_NrPeople(getContext());
	}

	/**
	 * @param context
	 * @return value of _NrPeople
	 */
	public final java.lang.Integer get_NrPeople(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._NrPeople.toString());
	}

	/**
	 * Set value of _NrPeople
	 * @param _nrpeople
	 */
	public final void set_NrPeople(java.lang.Integer _nrpeople)
	{
		set_NrPeople(getContext(), _nrpeople);
	}

	/**
	 * Set value of _NrPeople
	 * @param context
	 * @param _nrpeople
	 */
	public final void set_NrPeople(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _nrpeople)
	{
		getMendixObject().setValue(context, MemberNames._NrPeople.toString(), _nrpeople);
	}

	/**
	 * @return value of PersonListOperation_Person
	 */
	public final java.util.List<designpattern_callback.proxies.Person> getPersonListOperation_Person() throws com.mendix.core.CoreException
	{
		return getPersonListOperation_Person(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonListOperation_Person
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<designpattern_callback.proxies.Person> getPersonListOperation_Person(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<designpattern_callback.proxies.Person> result = new java.util.ArrayList<designpattern_callback.proxies.Person>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.PersonListOperation_Person.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(designpattern_callback.proxies.Person.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of PersonListOperation_Person
	 * @param personlistoperation_person
	 */
	public final void setPersonListOperation_Person(java.util.List<designpattern_callback.proxies.Person> personlistoperation_person)
	{
		setPersonListOperation_Person(getContext(), personlistoperation_person);
	}

	/**
	 * Set value of PersonListOperation_Person
	 * @param context
	 * @param personlistoperation_person
	 */
	public final void setPersonListOperation_Person(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<designpattern_callback.proxies.Person> personlistoperation_person)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (designpattern_callback.proxies.Person proxyObject : personlistoperation_person)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.PersonListOperation_Person.toString(), identifiers);
	}

	/**
	 * @return value of PersonListOperation_Project
	 */
	public final designpattern_callback.proxies.Project getPersonListOperation_Project() throws com.mendix.core.CoreException
	{
		return getPersonListOperation_Project(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonListOperation_Project
	 */
	public final designpattern_callback.proxies.Project getPersonListOperation_Project(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		designpattern_callback.proxies.Project result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PersonListOperation_Project.toString());
		if (identifier != null)
			result = designpattern_callback.proxies.Project.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PersonListOperation_Project
	 * @param personlistoperation_project
	 */
	public final void setPersonListOperation_Project(designpattern_callback.proxies.Project personlistoperation_project)
	{
		setPersonListOperation_Project(getContext(), personlistoperation_project);
	}

	/**
	 * Set value of PersonListOperation_Project
	 * @param context
	 * @param personlistoperation_project
	 */
	public final void setPersonListOperation_Project(com.mendix.systemwideinterfaces.core.IContext context, designpattern_callback.proxies.Project personlistoperation_project)
	{
		if (personlistoperation_project == null)
			getMendixObject().setValue(context, MemberNames.PersonListOperation_Project.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PersonListOperation_Project.toString(), personlistoperation_project.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return personListOperationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final designpattern_callback.proxies.PersonListOperation that = (designpattern_callback.proxies.PersonListOperation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DesignPattern_Callback.PersonListOperation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
