// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package designpattern_callback.proxies;

public class ProjectHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject projectHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DesignPattern_Callback.ProjectHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ProjectName("ProjectName"),
		NrPeople("NrPeople"),
		ReassignOrRemove("ReassignOrRemove");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProjectHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DesignPattern_Callback.ProjectHelper"));
	}

	protected ProjectHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject projectHelperMendixObject)
	{
		if (projectHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DesignPattern_Callback.ProjectHelper", projectHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DesignPattern_Callback.ProjectHelper");

		this.projectHelperMendixObject = projectHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ProjectHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static designpattern_callback.proxies.ProjectHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return designpattern_callback.proxies.ProjectHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static designpattern_callback.proxies.ProjectHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new designpattern_callback.proxies.ProjectHelper(context, mendixObject);
	}

	public static designpattern_callback.proxies.ProjectHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return designpattern_callback.proxies.ProjectHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ProjectName
	 */
	public final java.lang.String getProjectName()
	{
		return getProjectName(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectName
	 */
	public final java.lang.String getProjectName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProjectName.toString());
	}

	/**
	 * Set value of ProjectName
	 * @param projectname
	 */
	public final void setProjectName(java.lang.String projectname)
	{
		setProjectName(getContext(), projectname);
	}

	/**
	 * Set value of ProjectName
	 * @param context
	 * @param projectname
	 */
	public final void setProjectName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String projectname)
	{
		getMendixObject().setValue(context, MemberNames.ProjectName.toString(), projectname);
	}

	/**
	 * @return value of NrPeople
	 */
	public final java.lang.String getNrPeople()
	{
		return getNrPeople(getContext());
	}

	/**
	 * @param context
	 * @return value of NrPeople
	 */
	public final java.lang.String getNrPeople(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NrPeople.toString());
	}

	/**
	 * Set value of NrPeople
	 * @param nrpeople
	 */
	public final void setNrPeople(java.lang.String nrpeople)
	{
		setNrPeople(getContext(), nrpeople);
	}

	/**
	 * Set value of NrPeople
	 * @param context
	 * @param nrpeople
	 */
	public final void setNrPeople(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nrpeople)
	{
		getMendixObject().setValue(context, MemberNames.NrPeople.toString(), nrpeople);
	}

	/**
	 * Set value of ReassignOrRemove
	 * @param reassignorremove
	 */
	public final designpattern_callback.proxies.Enum_PersonlistAction getReassignOrRemove()
	{
		return getReassignOrRemove(getContext());
	}

	/**
	 * @param context
	 * @return value of ReassignOrRemove
	 */
	public final designpattern_callback.proxies.Enum_PersonlistAction getReassignOrRemove(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ReassignOrRemove.toString());
		if (obj == null)
			return null;

		return designpattern_callback.proxies.Enum_PersonlistAction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ReassignOrRemove
	 * @param reassignorremove
	 */
	public final void setReassignOrRemove(designpattern_callback.proxies.Enum_PersonlistAction reassignorremove)
	{
		setReassignOrRemove(getContext(), reassignorremove);
	}

	/**
	 * Set value of ReassignOrRemove
	 * @param context
	 * @param reassignorremove
	 */
	public final void setReassignOrRemove(com.mendix.systemwideinterfaces.core.IContext context, designpattern_callback.proxies.Enum_PersonlistAction reassignorremove)
	{
		if (reassignorremove != null)
			getMendixObject().setValue(context, MemberNames.ReassignOrRemove.toString(), reassignorremove.toString());
		else
			getMendixObject().setValue(context, MemberNames.ReassignOrRemove.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return projectHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final designpattern_callback.proxies.ProjectHelper that = (designpattern_callback.proxies.ProjectHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DesignPattern_Callback.ProjectHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
