// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package designpattern_callback.proxies;

public class ReassignOperation extends designpattern_callback.proxies.PersonListOperation
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DesignPattern_Callback.ReassignOperation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OperationLabel("OperationLabel"),
		_NrPeople("_NrPeople"),
		ReassignOperation_Project("DesignPattern_Callback.ReassignOperation_Project"),
		PersonListOperation_Person("DesignPattern_Callback.PersonListOperation_Person"),
		PersonListOperation_Project("DesignPattern_Callback.PersonListOperation_Project");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReassignOperation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DesignPattern_Callback.ReassignOperation"));
	}

	protected ReassignOperation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reassignOperationMendixObject)
	{
		super(context, reassignOperationMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DesignPattern_Callback.ReassignOperation", reassignOperationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DesignPattern_Callback.ReassignOperation");
	}

	/**
	 * @deprecated Use 'ReassignOperation.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static designpattern_callback.proxies.ReassignOperation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return designpattern_callback.proxies.ReassignOperation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static designpattern_callback.proxies.ReassignOperation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new designpattern_callback.proxies.ReassignOperation(context, mendixObject);
	}

	public static designpattern_callback.proxies.ReassignOperation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return designpattern_callback.proxies.ReassignOperation.initialize(context, mendixObject);
	}

	/**
	 * @return value of ReassignOperation_Project
	 */
	public final designpattern_callback.proxies.Project getReassignOperation_Project() throws com.mendix.core.CoreException
	{
		return getReassignOperation_Project(getContext());
	}

	/**
	 * @param context
	 * @return value of ReassignOperation_Project
	 */
	public final designpattern_callback.proxies.Project getReassignOperation_Project(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		designpattern_callback.proxies.Project result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReassignOperation_Project.toString());
		if (identifier != null)
			result = designpattern_callback.proxies.Project.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReassignOperation_Project
	 * @param reassignoperation_project
	 */
	public final void setReassignOperation_Project(designpattern_callback.proxies.Project reassignoperation_project)
	{
		setReassignOperation_Project(getContext(), reassignoperation_project);
	}

	/**
	 * Set value of ReassignOperation_Project
	 * @param context
	 * @param reassignoperation_project
	 */
	public final void setReassignOperation_Project(com.mendix.systemwideinterfaces.core.IContext context, designpattern_callback.proxies.Project reassignoperation_project)
	{
		if (reassignoperation_project == null)
			getMendixObject().setValue(context, MemberNames.ReassignOperation_Project.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReassignOperation_Project.toString(), reassignoperation_project.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final designpattern_callback.proxies.ReassignOperation that = (designpattern_callback.proxies.ReassignOperation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DesignPattern_Callback.ReassignOperation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
