// This file was generated by Mendix Modeler 7.18.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package designpattern_singleton.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DesignPattern_Singleton module
	public static boolean bCo_AloneOnTheWorld(IContext context, designpattern_singleton.proxies.AloneOnTheWorld _aloneOnTheWorld)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AloneOnTheWorld", _aloneOnTheWorld == null ? null : _aloneOnTheWorld.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "DesignPattern_Singleton.BCo_AloneOnTheWorld", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bCr_AloneOnTheWorld(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "DesignPattern_Singleton.BCr_AloneOnTheWorld", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_AloneOnTheWorld_New(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "DesignPattern_Singleton.MB_AloneOnTheWorld_New", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static designpattern_singleton.proxies.AloneOnTheWorld sUB_AloneOnTheWorld_GetOrCreate(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "DesignPattern_Singleton.SUB_AloneOnTheWorld_GetOrCreate", params);
			return result == null ? null : designpattern_singleton.proxies.AloneOnTheWorld.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}