// This file was generated by Mendix Modeler 7.18.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package designpattern_strategy.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DesignPattern_Strategy module
	public static boolean bCo_PayCalculatorOvertime(IContext context, designpattern_strategy.proxies.Overtime _overtimePayCalculator)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("OvertimePayCalculator", _overtimePayCalculator == null ? null : _overtimePayCalculator.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "DesignPattern_Strategy.BCo_PayCalculatorOvertime", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bCo_PayCalculatorStandard(IContext context, designpattern_strategy.proxies.Standard _standardPayCalculator)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("StandardPayCalculator", _standardPayCalculator == null ? null : _standardPayCalculator.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "DesignPattern_Strategy.BCo_PayCalculatorStandard", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void bCr_PayCalculatorOvertime_SetType(IContext context, designpattern_strategy.proxies.PayCalculator _payCalculator)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("PayCalculator", _payCalculator == null ? null : _payCalculator.getMendixObject());
			Core.execute(context, "DesignPattern_Strategy.BCr_PayCalculatorOvertime_SetType", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void bCr_PayCalculatorStandard_SetType(IContext context, designpattern_strategy.proxies.PayCalculator _payCalculator)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("PayCalculator", _payCalculator == null ? null : _payCalculator.getMendixObject());
			Core.execute(context, "DesignPattern_Strategy.BCr_PayCalculatorStandard_SetType", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static designpattern_strategy.proxies.Project1 dS_Project1_Create(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "DesignPattern_Strategy.DS_Project1_Create", params);
			return result == null ? null : designpattern_strategy.proxies.Project1.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static designpattern_strategy.proxies.Project2 dS_Project2_Create(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "DesignPattern_Strategy.DS_Project2_Create", params);
			return result == null ? null : designpattern_strategy.proxies.Project2.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static designpattern_strategy.proxies.Project3 dS_Project3_Create(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "DesignPattern_Strategy.DS_Project3_Create", params);
			return result == null ? null : designpattern_strategy.proxies.Project3.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_Project2_CalculateTypeOvertime(IContext context, designpattern_strategy.proxies.Project2 _project2)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project2", _project2 == null ? null : _project2.getMendixObject());
			Core.execute(context, "DesignPattern_Strategy.MB_Project2_CalculateTypeOvertime", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_Project2_CalculateTypeStandard(IContext context, designpattern_strategy.proxies.Project2 _project2)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project2", _project2 == null ? null : _project2.getMendixObject());
			Core.execute(context, "DesignPattern_Strategy.MB_Project2_CalculateTypeStandard", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_Project3_CalculateTypeOvertime(IContext context, designpattern_strategy.proxies.Project3 _project3)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project3", _project3 == null ? null : _project3.getMendixObject());
			Core.execute(context, "DesignPattern_Strategy.MB_Project3_CalculateTypeOvertime", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_Project3_CalculateTypeStandard(IContext context, designpattern_strategy.proxies.Project3 _project3)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project3", _project3 == null ? null : _project3.getMendixObject());
			Core.execute(context, "DesignPattern_Strategy.MB_Project3_CalculateTypeStandard", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String project_GenerateReport_v1(IContext context, designpattern_strategy.proxies.Project1 _project)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project", _project == null ? null : _project.getMendixObject());
			return (java.lang.String)Core.execute(context, "DesignPattern_Strategy.Project_GenerateReport_v1", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String project_GenerateReport_v2(IContext context, designpattern_strategy.proxies.Project2 _project, designpattern_strategy.proxies.Enum_BillType _billType)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project", _project == null ? null : _project.getMendixObject());
			params.put("BillType", _billType == null ? null : _billType.name());
			return (java.lang.String)Core.execute(context, "DesignPattern_Strategy.Project_GenerateReport_v2", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String project_GenerateReport_v3(IContext context, designpattern_strategy.proxies.Project3 _project, designpattern_strategy.proxies.PayCalculator _payCalculator)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Project", _project == null ? null : _project.getMendixObject());
			params.put("PayCalculator", _payCalculator == null ? null : _payCalculator.getMendixObject());
			return (java.lang.String)Core.execute(context, "DesignPattern_Strategy.Project_GenerateReport_v3", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}