// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package designpattern_visitor.proxies;

public class Count extends designpattern_visitor.proxies.Visitor
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DesignPattern_Visitor.Count";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HeadCount("HeadCount"),
		HeadCountFemales("HeadCountFemales"),
		Visitor_TreeNode("DesignPattern_Visitor.Visitor_TreeNode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Count(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DesignPattern_Visitor.Count"));
	}

	protected Count(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countMendixObject)
	{
		super(context, countMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DesignPattern_Visitor.Count", countMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DesignPattern_Visitor.Count");
	}

	/**
	 * @deprecated Use 'Count.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static designpattern_visitor.proxies.Count initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return designpattern_visitor.proxies.Count.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static designpattern_visitor.proxies.Count initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new designpattern_visitor.proxies.Count(context, mendixObject);
	}

	public static designpattern_visitor.proxies.Count load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return designpattern_visitor.proxies.Count.initialize(context, mendixObject);
	}

	/**
	 * @return value of HeadCount
	 */
	public final java.lang.Integer getHeadCount()
	{
		return getHeadCount(getContext());
	}

	/**
	 * @param context
	 * @return value of HeadCount
	 */
	public final java.lang.Integer getHeadCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.HeadCount.toString());
	}

	/**
	 * Set value of HeadCount
	 * @param headcount
	 */
	public final void setHeadCount(java.lang.Integer headcount)
	{
		setHeadCount(getContext(), headcount);
	}

	/**
	 * Set value of HeadCount
	 * @param context
	 * @param headcount
	 */
	public final void setHeadCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer headcount)
	{
		getMendixObject().setValue(context, MemberNames.HeadCount.toString(), headcount);
	}

	/**
	 * @return value of HeadCountFemales
	 */
	public final java.lang.Integer getHeadCountFemales()
	{
		return getHeadCountFemales(getContext());
	}

	/**
	 * @param context
	 * @return value of HeadCountFemales
	 */
	public final java.lang.Integer getHeadCountFemales(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.HeadCountFemales.toString());
	}

	/**
	 * Set value of HeadCountFemales
	 * @param headcountfemales
	 */
	public final void setHeadCountFemales(java.lang.Integer headcountfemales)
	{
		setHeadCountFemales(getContext(), headcountfemales);
	}

	/**
	 * Set value of HeadCountFemales
	 * @param context
	 * @param headcountfemales
	 */
	public final void setHeadCountFemales(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer headcountfemales)
	{
		getMendixObject().setValue(context, MemberNames.HeadCountFemales.toString(), headcountfemales);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final designpattern_visitor.proxies.Count that = (designpattern_visitor.proxies.Count) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DesignPattern_Visitor.Count";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
